### ISSUE TITLE
Updating from Niko version

### ISSUE THREAD

**Issue by mloveless1227** [fluffyst/Surftimer#23]
After using the new SQL file to update the DB from Niko's version to yours, I'm having a couple of strange issues. 

Executing the SQL against Niko's version DB worked fine, no errors at all. I manually checked over the tables and everything appears correct. 

The problem happens in game. None of the zone markers appear and the timer will not start. The reason it's strange is because the plugin is recognizing where zones are made. It just will not show the zone markers for them and it sounds a buzzer every time you go through where the zone should be. When I open the zone menu and edit the existing zone, the zone markers appear and it allows me to edit it, but after I save, it disappears. I have also tried deleting zones and rezoning them fresh with your plugin, they still do not physically appear but they are saving because when you attempt to jump out of them, a buzzer sounds but the timer does not start.

I have tried all the various "zone display" settings (all sides, only bottoms, none at all), verified which zones are shown is correct (start and end), the plugin is reading all zones from DB, and I also verified that I have the Decals folder on the server, the fastDL (as both the vmt/vtf files, and bzipped versions), and on my client, all exist as they should. 

Permissions with my DB are all correct. It's not having any issues reading nor writing to. 

Any idea what could be going on?

**Comment by fluffyst** [comment]
would you mind sending me a dump of your db? also `!showzones` will most likely make them appear

**Comment by fluffyst** [comment]
How'd you manage to fix the issue? Curious in case I need to fix something so others don't have the same problem

**Comment by mloveless1227** [comment]
I definitely did not mean to close this. I started typing a reply then closed it because I thought of something I wanted to try first before commenting. I must have done something wrong. Sorry about that, problem still persists. Just was looking into a couple other things before following up.

**Comment by fluffyst** [comment]
Ah, all good.

**Comment by mloveless1227** [comment]
Showzones did not do anything but make the zones appear, but instead of appearing as they are set in the config (bottom of zones only, show only start and end), they appear in their 3D entirety, and every zone shows. Regardless, the timer still will not start, just makes the buzzer sound when you exit the zone and it locks you into the prespeed cap. 

I'm unsure about dumping my db, I don't know what that's going to resolve exactly. Please don't take it the wrong way it's just that there is 3+ years worth of zoned maps and player information in that DB. I'm assuming that even just installing Niko's DB version and premade zones then running the DB update should give the same results. 

Also, there are no errors or logs of any kind outputting in regards to this. I think I forgot to mention that in my first post.

**Comment by fluffyst** [comment]
you can just give me a dump with data in the ck_zones table, don't need the rest of the data, it will make it easier for me to see if I can replicate

**Comment by mloveless1227** [comment]
https://drive.google.com/file/d/0B-b8dlaD8kE8OWxadnRTS1NVOVU/view?usp=sharing

I included the ck_zones dump original from my working db, as well as the dump after running your upgrade.sql file.

**Comment by fluffyst** [comment]
Thanks, re-run the upgarde-niko.sql file on your old database and it should work now

**Comment by mloveless1227** [comment]
Just finished testing. After running the new upgrade file, the timer will now start when I leave the zoned area, ends when I enter the zoned end area, and records my time fine.

However, it is still not showing the specified zones, in my case that's start and end zones with only the bottom part of the zone. If I type !showzones, the zones do appear in their full 3D form, but not as specified in the config (or through the admin menu). 

Also, it seems to not be retaining my speed starts. I double checked all the settings are correct, and that it's still zoned right, but any time I go into a speed start zone it drops me back down to whatever pre-start speed that's set, like 280 or something like that.

**Comment by fluffyst** [comment]
does it work normally if you use a normal start zone? and currently the !showzones thing is because it's hard coded to only show zones when you do !showzones and show all, make a issue about this so i remember to fix it later

**Comment by mloveless1227** [comment]
Normal start zones work properly. Speed starts do not. Neither ones I've already made or ones that I make new inside yours. I set the sm_startprespeed but it does not change anything. 

For instance, when Im on Kitsune or utopia_njv, and I go to telehop through the floor and out my speed start zone, I don't start fast and get knocked down to below a speed cap, the telehop just does not work. I come out at the back of the start zone just jumping normally if I'm holding space bar, as where it should be shooting me out at around 3000 speed.

Would be great to have the zones showing as well man. I love the changes you are making but if you're going to release this publicly, you should try to make it a little more user friendly instead of hard coded specific to your servers. Although I understand it's your choice to do what you want. Myself and many other are looking for a fork to stay committed to because this plugin is in desperate need of updating but changing too many basic features is going to make it difficult.

**Comment by fluffyst** [comment]
I hard coded things LONG before I planned to release this, so that's why I just want ppl to make a issue about what was previously hard coded so I remember to fix it or add onto it, it doesn't take very long for me to change it back, next update will be me un-hardcoding everything. Will fix ur issue soon, temp fix would be to just use start zones, speed starts will be depreciated anyway

**Comment by mloveless1227** [comment]
Depreciating speed start zones? The ability to telehop are built into these maps, seems silly to completely remove the ability to use the maps design when it's currently adjustable via a simple convar. 

Anyway, that's your choice. Just providing feedback for whats available. Thanks for all your follow up.

**Comment by fluffyst** [comment]
Not removing the ability to telehop, just speed start zones, because like you said, a simple convar can already make normal start zones do the exact same thing, I don't really see a use in having two start zone types, doing `sm_sps 0` on a map that requires telehopping will do exactly what you're looking for, without having to change the zone type into a `speed start` , if you get what I mean

**Comment by mloveless1227** [comment]
I'm going to close this issue as it seems to be resolved from what I can tell. Thank you very much for your prompt responses and work. 

On a personal note, I hope you keep working at this, but I'm appreciate of the things you have done either way. If you ever need an extra person to test anything, I'm generally free to help out. 

http://steamcommunity.com/id/kmsraidboss/

**Comment by M-archand** [comment]
Was there no resolve to this? I've just updated from Niko's version and I'm having almost the same issue. I've converted my db without any errors, my zones show, and the timer starts... however if I change my start or end zones (stretch/redraw) then the timer doesn't start anymore.

**Comment by fluffyst** [comment]
Are you trying to change them on a map that you rezoned with hook zones?

**Comment by M-archand** [comment]
Thanks for the quick reply, but it was my mistake. I somehow lost some formatting in my db.ck_zones that was causing the issue, I restored from a backup and it resolved the issue.
